### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by ninjakaib** [JeremiahPetersen/RepoToText#5]
Love using this but I feel like I'm staring into the sun when doing homework late at night

**Comment by JeremiahPetersen** [comment]
ah good idea.  forgot to add that.  will include it on the next update coming within one week.  thanks for mentioning

**Comment by JeremiahPetersen** [comment]
@ninjakaib Dark Mode has been added!  I appreciate your patience, eclipse glasses needed no more ;)

**Comment by ninjakaib** [comment]
Awesome!
